ALTER TABLE DEX_CHRGACCT
  DROP CONSTRAINT IF EXISTS DEX_CHRGACCT_pk

ALTER TABLE DEX_CHRGACCT
DROP COLUMN IF EXISTS CHRGACCT_SEQ_NUM;

alter table DEX_CHRGACCT
add CHRGACCT_SEQ_NUM int identity(1,1)

ALTER TABLE DEX_CHRGACCT
  ADD CONSTRAINT DEX_CHRGACCT_pk 
    PRIMARY KEY (CHRGACCT_SEQ_NUM);