-- ===================================================================================
-- Create Schema Template for Azure SQL Database and Azure SQL Data Warehouse Database
-- ===================================================================================

CREATE SCHEMA ALIGNE

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_BOOK;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_CONTRACT;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_CONTRACTAUX;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_CPTY;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_CPTYAUX;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_MKT;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_MRKTC;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_SAP_MASTER_TRADES;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_USR;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_TPOWAUX;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_TPOW2;

ALTER SCHEMA ALIGNE 
    TRANSFER dbo.ALIGNE_TPOW;

CREATE SCHEMA GLEIF

ALTER SCHEMA GLEIF
    TRANSFER dbo.GLEIF;



-- MCC schema migration

CREATE SCHEMA MCC

ALTER SCHEMA MCC
    TRANSFER dbo.MCC_COMMITMENT;

ALTER SCHEMA MCC
    TRANSFER dbo.MCC_CASE;

ALTER SCHEMA MCC
    TRANSFER dbo.MCC_TRADED_INSTRUMENT;

ALTER SCHEMA MCC
    TRANSFER dbo.MCC_NOTE;

ALTER SCHEMA MCC
    TRANSFER dbo.MCC_DOC_CONTRACT_XREF;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_CASE_DOC_XREF;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_CASE_AUDIT;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_COMP_REPORTABLE_ENTITY;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_CONTRACT;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_CONTRACT_DISPUTE;
	
	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_DISPUTE;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_KPI_CREPORT;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_ECONFIRM_OPEN_TRADE;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_IFACE_STAGING;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_MASTER_AGREEMENT;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_PARTY;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_PERSONNEL;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_PROCESS_INSTANCE;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_QUEUE;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_UNIT;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_M2M;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_WORKFLOW;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_ECONFIRM_REPORT;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_ECONFIRM_TRADE_DETAIL;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_ECONFIRM_DATA_SUBMIT;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_IFACE;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_ECONFIRM_ERROR_LOG ;

	ALTER SCHEMA MCC
    TRANSFER dbo.MCC_IFACE_STAGING_M2M;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_IFACE_M2M;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_DOC_CATEGORY;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_DOC_DEX_XREF;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_DOC_XREF;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_DOC_DOCUMENT;

	ALTER SCHEMA MCC
    TRANSFER dbo.CCM_DOC_FOLDER;

select count(*) from MCC.COMMITMENT
select top 1 * from MCC.CCM_DOC_DOCUMENT

truncate table MCC.CCM_DOC_DOCUMENT

ALTER TABLE MCC.CCM_DOC_DOCUMENT
ADD PRIMARY KEY (DOC_KEY);

select count(*) from MCC.CCM_DOC_DOCUMENT
select count(distinct DOC_KEY) from MCC.CCM_DOC_DOCUMENT

select * from MCC.CCM_DOC_DOCUMENT not in select 

-- Finding the data with duplicate keys for CCM_DOC_DOCUMENT
SELECT * FROM MCC.CCM_DOC_DOCUMENT WHERE DOC_KEY IN
  (SELECT DOC_KEY FROM MCC.CCM_DOC_DOCUMENT GROUP BY DOC_KEY HAVING COUNT(*) > 1)
  ORDER BY DOC_KEY

SELECT USER_NAME(member_principal_id) AS [Owner]
FROM sys.database_role_members
WHERE USER_NAME(role_principal_id) = 'db_owner'
    AND USER_NAME(member_principal_id) != 'dbo'

select count(*) from MCC.CCM_DOC_DEX_XREF
select top 1 * from MCC.CCM_DOC_DEX_XREF

-- DEX Schema Migration


CREATE SCHEMA DEX


ALTER SCHEMA DEX
    TRANSFER dbo.DEX_CORPENT;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_COMPANY;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_CHRGACCT;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_COMPADDR;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_EVNTNARR;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_FUTFWDEX;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_GRADE;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_NEWTRADE;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_PRCGPRDD;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_PRICING;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_TRDGACCT;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_CONTRACT;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_CONDISPT;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_PRCLDCH;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_CDTYCTMT;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_PARCEL;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_PRCLCST;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_CNCHEVNT;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_CONSTOPR;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_ADDRLINE;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_GRADEGP;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_USR;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_PROFGP;

ALTER SCHEMA DEX
    TRANSFER dbo.DEX_LOCATION;



   

   