CREATE LOGIN MDENTON WITH password='NewTestLOG342';

CREATE USER MDENTON FROM LOGIN MDENTON;

CREATE USER MDENTON FROM LOGIN MDENTON;

use gcpipeline
 GRANT SELECT ON OBJECT::[dbo].[vw_VIEWTEST] TO MDENTON

